services:
  - type: web
    name: langbridge-backend
    env: node
    rootDir: ./backend
    buildCommand: cd backend && npm install && pip install -r requirements.txt
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: langbridge-frontend
    env: node
    rootDir: ./frontend
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm run dev
    envVars:
      - key: NODE_ENV
        value: production
