services:
  - type: web
    name: langbridge-backend
    env: node
    buildCommand: cd backend && npm install && pip install -r requirements.txt
    startCommand: cd backend && npm run dev
    rootDir: .
